# Generated by Django 5.1.1 on 2024-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productentry_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
