# Generated by Django 5.1.1 on 2024-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_productentry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='price',
            field=models.IntegerField(),
        ),
    ]
